"""Build portfolio provenance from the reviewed local repository revisions.
Run after refreshing screenshots and exports; this does not pull or modify repositories.
"""
from pathlib import Path
import json
import subprocess

ROOT = Path(__file__).resolve().parents[1]
projects = [
    dict(id="watch", title="Watch Atlas", repo="watch-atlas", local="/private/tmp/portfolio-watch-atlas", category="interactive", eyebrow="A study in time", description="Explore 1,629 wristwatch references through case sizes, movements, gemstones and collection patterns.", tags=["Data storytelling", "Interactive catalog", "JavaScript"], metric="1,629", metricLabel="watch references", liveUrl="https://www.arunabhosom.com/watch-atlas/", demo="watch", change="Searchable collection insights now connect chart selections to matching watch references.", pipeline=["Prepare seven source tables", "Normalize brand and reference", "Explore five watchmakers"], limitation="The catalog is an archival 2023–2024 snapshot. Segment labels are inferred; specifications and prices are not live market data.", images=[("watch-atlas.png","The watch collection overview","Captured from the public app"),("watch-insights.png","Compare catalog mix, case sizes and movement families","2023–2024 collection snapshot")]),
    dict(id="playerpulse", title="PlayerPulse", repo="PlayerPulse-soccer-comparison-dashboard", local="/Users/Arunabho/Documents/soccer comparison dashboard", category="interactive", eyebrow="The beautiful game, in numbers", description="Compare footballers at the same age, explore per-90 metrics, and inspect World Cup match coverage.", tags=["React", "Sports analytics", "Data pipelines"], metric="Per 90", metricLabel="player comparisons", private=True, demo=None, change="The local project includes an age-based comparison workspace, World Cup views and a permission-gated match-log pipeline.", pipeline=["Prepare player and match sources", "Align age and metric coverage", "Compare like-for-like records"], limitation="Captured from the local working tree. Data coverage differs by player, season and source. The source repository is private; no public live deployment was verified.", images=[("playerpulse-compare.png","Age-based player comparison workspace","Local project capture"),("playerpulse-worldcup.png","World Cup data center","Local project capture")]),
    dict(id="intelligence", title="Competitive Intelligence", repo="Threat_scoring_app", local="/Users/Arunabho/Desktop/Threat_scoring_app", category="ai", eyebrow="From scattered signals to context", description="Bring hiring, technology shifts and company signals into one research workspace with an explainable view of the evidence.", tags=["React + FastAPI", "PostgreSQL", "n8n"], metric="3", metricLabel="new intelligence modules", demo="talent", change="Insight Engine, Talent Radar and Scraper Lab join scoring services and automated n8n workflows.", pipeline=["Collect company signals", "Aggregate and score evidence", "Explore trends and hiring"], limitation="UI screenshots use clearly labelled fictional API fixtures. The public walkthrough uses synthetic jobs. Production data requires the project’s backend and database.", images=[("threat-insight-engine.png","Insight Engine: filters, company profile and signals","Original interface · fictional sample data"),("threat-talent-radar.png","Talent Radar: hiring markets and capability lanes","Original interface · fictional sample jobs"),("threat-competitive-profile.png","Competitive Profile: compare company signals","Original interface · fictional sample data")]),
    dict(id="country", title="Country Memory Map", repo="country-memory-map", local="/Users/Arunabho/Developer/country-memory-map", category="interactive", eyebrow="A little curiosity goes a long way", description="Learn countries, capitals and flags through a responsive map, solo challenges and multiplayer rooms.", tags=["Interactive maps", "Game systems", "JavaScript"], metric="195", metricLabel="countries to discover", liveUrl="https://www.arunabhosom.com/country-memory-map/", demo="country", change="One geography arcade brings map exploration, country and capital challenges, flag games and private multiplayer rooms together.", pipeline=["Share one country model", "Apply game and scoring rules", "Play, explore and practise"], limitation="Optional voice input depends on browser support. Multiplayer requires the public room service; solo play and map exploration are available separately.", images=[("country-memory-map.png","The geography arcade home","Captured from the public app"),("country-explore.png","Country and capital recognition on the world map","Captured from the public app")]),
    dict(id="fraud", title="Credit Card Fraud Detection", repo="Credit-Card-Fraud-Detection", local="/Users/Arunabho/Developer/Credit-Card-Fraud-Detection", category="ai", eyebrow="Make the trade-off visible", description="Detect rare fraud while showing how investigation capacity changes captured fraud and false alerts.", tags=["Calibrated ML", "Chronological holdout", "Python"], metric="0.7882", metricLabel="test average precision", demo="fraud", report="results/phase2/REPORT.md", change="The full benchmark now includes independent calibration, uncertainty intervals, stability checks and frozen review policies.", pipeline=["Deduplicate public transactions", "Calibrate on a separate reserve", "Evaluate later held-out records"], limitation="A retrospective, anonymized benchmark spanning two days. Recorded precision is 90.2% and recall 74.3% at the validation-selected threshold; these are not production guarantees.", images=[("fraud-ranking.png","Fraud capture versus investigation budget","Published phase-two benchmark output"),("fraud-reliability.png","Calibration reliability and bin support","Published phase-two benchmark output")]),
    dict(id="churn", title="Predictive Employee Churn", repo="Predictive-Employee-Churn", local="/Users/Arunabho/Developer/Predictive-Employee-Churn", category="ai", eyebrow="Predictions with an evidence trail", description="Evaluate employee departure classification with calibrated probabilities, uncertainty and auditable error patterns.", tags=["Random Forest", "Calibration", "Error analysis"], metric="0.9593", metricLabel="test average precision", demo="churn", report="results/phase2/REPORT.md", change="Independent calibration, error audits and development-only stability checks make the benchmark’s strengths and limits visible.", pipeline=["Deduplicate the HR benchmark", "Isolate fit and calibration", "Audit held-out errors"], limitation="This public teaching benchmark has no dated employee observations or defined prediction horizon. Recorded associations are not causal explanations or grounds for individual employment decisions.", images=[("churn-reliability.png","Employee churn calibration and sample support","Published phase-two benchmark output"),("churn-ranking.png","Departure capture across review budgets","Published phase-two benchmark output")]),
    dict(id="agoda", title="Agoda Booking Analysis", repo="Agoda-Booking-Analysis", local="/Users/Arunabho/Desktop/Agoda-Booking-Analysis", category="analytics", eyebrow="Understand when people book", description="Explore booking lead times, daily rates and accommodation patterns across five cities with a reproducible analysis.", tags=["Python", "Pandas", "Data validation"], metric="6", metricLabel="reproducible chart outputs", demo="agoda", change="A shared notebook and CLI workflow now validates inputs, reports excluded rows and produces six charts with CSV summaries.", pipeline=["Validate booking fields", "Summarize nonoverlapping groups", "Explore counts and booked rates"], limitation="The original workbook is absent. Portfolio charts and filters use 1,000 deterministic synthetic bookings, not Agoda business findings or a price forecast.", images=[("agoda-cities.png","Booking counts and average rates by city","Original analysis output · synthetic demo"),("agoda-lead_time.png","Nonoverlapping booking lead-time intervals","Original analysis output · synthetic demo"),("agoda-daily_trends.png","Daily booking and booked-rate trends","Original analysis output · synthetic demo")]),
]
for project in projects:
    source=project.pop("local")
    project["snapshotCommit"]=subprocess.check_output(["git","-C",source,"rev-parse","HEAD"],text=True).strip()
    project["snapshotDate"]=subprocess.check_output(["git","-C",source,"log","-1","--format=%cI"],text=True).strip()
    project["snapshotMessage"]=subprocess.check_output(["git","-C",source,"log","-1","--format=%s"],text=True).strip()
    project["capturedOn"]="2026-09-30"
    project["workingTreeChanges"]=bool(subprocess.check_output(["git","-C",source,"status","--porcelain"],text=True).strip())
    project["sourceUrl"]="https://github.com/AarunabhS/"+project["repo"]
    if project["id"] in {"fraud", "churn"}:
        label="Fraud precision, review capacity and score separation" if project["id"]=="fraud" else "Model signals, department uncertainty and calibration"
        project["images"].insert(0,(project["id"]+"-overview.png",label,"Published project summary · retrospective benchmark"))
        project["change"]+=" A new results gallery brings the key charts together in one visual summary."
    if project["id"]=="fraud":
        project["images"].append(("fraud-demo.png","Fraud Operations Lab: scoring examples and review policies","Captured from the local project demo"))
    if project["id"]=="playerpulse":
        project["demo"]="playerpulse"
        project["images"].insert(1,("playerpulse-metrics.png","Recorded player statistics compared at the same age","Local project capture · coverage varies by metric"))
    project["images"]=[{"src":"images/outputs/"+src,"preview":"images/outputs/previews/"+src.replace(".png",".webp"),"alt":alt,"caption":caption} for src,alt,caption in project["images"]]
(ROOT/"data/projects.json").write_text(json.dumps({"capturedOn":"2026-09-30","projects":projects},indent=2)+"\n")
print("Wrote seven reviewed projects with screenshot and source provenance.")
