"""Export the updated Agoda repository's deterministic demo for the portfolio.

Usage: python scripts/export-bookings.py /path/to/Agoda-Booking-Analysis
The source repository is read only. No business workbook is used.
"""
import importlib.util
import json
import os
from pathlib import Path
import subprocess
import sys

os.environ.setdefault("MPLCONFIGDIR", "/tmp/portfolio-matplotlib")
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parents[1]
source = Path(sys.argv[1]).resolve()
spec = importlib.util.spec_from_file_location("booking_analysis", source / "analysis.py")
analysis = importlib.util.module_from_spec(spec)
spec.loader.exec_module(analysis)
frame, audit = analysis.prepare_data(analysis.demo_data(seed=42, rows=1000))
tables = analysis.summarize(frame)
data_dir = ROOT / "data"
image_dir = ROOT / "images" / "outputs"
data_dir.mkdir(exist_ok=True)
image_dir.mkdir(parents=True, exist_ok=True)
columns = ["booking_date", "city_id", "ADR_USD", "star_rating", "accommodation_type_name", "lead_time", "lead_time_bucket"]
export = frame[columns].copy()
export["booking_date"] = export["booking_date"].dt.strftime("%Y-%m-%d")
export["lead_time_bucket"] = export["lead_time_bucket"].astype(str)
payload = {
    "source": "Synthetic demo generated by Agoda-Booking-Analysis/analysis.py",
    "seed": 42,
    "commit": subprocess.check_output(["git", "-C", str(source), "rev-parse", "HEAD"], text=True).strip(),
    "audit": audit,
    "rows": json.loads(export.to_json(orient="records")),
}
(data_dir / "bookings.json").write_text(json.dumps(payload, separators=(",", ":")) + "\n")
for name, figure in analysis.make_plots(tables, "SYNTHETIC DEMO").items():
    figure.savefig(image_dir / f"agoda-{name}.png", dpi=150)
    plt.close(figure)
for name, table in tables.items():
    table.to_csv(data_dir / f"agoda-{name}.csv")
(data_dir / "agoda-data-quality.json").write_text(json.dumps({**audit, "source": "SYNTHETIC DEMO"}, indent=2) + "\n")
print(f"Exported {audit['valid_rows']} synthetic bookings and six original analysis charts.")
